// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxoykmrcjzehxcxvqee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveG95a21yY2p6ZWh4Y3h2cWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTk3MjEsImV4cCI6MjA2MTgzNTcyMX0.5jPvvTPdWOSAboGJutHPiaXngSMf0KSUexN7ly3d_bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);